name: Investor Workflow

on: [push]

jobs:
  deploy:
    name: CD Pipeline PRD
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/html/investordashboard
            sudo git stash
            sudo git pull origin master
            sudo composer install --optimize-autoloader --no-dev
            sudo npm install
            sudo npm run production
            sudo php artisan config:cache
            sudo php artisan queue:restart
          host: ${{ secrets.HOST }}
          user: ubuntu
          key: ${{ secrets.PRIVATE_KEY}}

#  npm:
#      runs-on: ubuntu-latest
#
#      strategy:
#        matrix:
#          node-version: [12.x]
#
#      steps:
#      - uses: actions/checkout@v2
#
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - run: npm install
#      - run: npm run prod
#
#
#      - name: Copying files to server
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ubuntu
#          rm: true
#          key: ${{ secrets.PRIVATE_KEY }}
#          source: "public/"
#          target: "/var/www/html/investordashboard/public/"

